//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrepaCH.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrepaCH.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backpack 04.
        /// </summary>
        internal static string Chk_Backpack04 {
            get {
                return ResourceManager.GetString("Chk-Backpack04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayonet.
        /// </summary>
        internal static string Chk_Bayonet {
            get {
                return ResourceManager.GetString("Chk-Bayonet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beret 95 with Brigade Insignia.
        /// </summary>
        internal static string Chk_Beret {
            get {
                return ResourceManager.GetString("Chk-Beret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine bonnet.
        /// </summary>
        internal static string Chk_BonnetMarin {
            get {
                return ResourceManager.GetString("Chk-BonnetMarin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot cleaning kit.
        /// </summary>
        internal static string Chk_BootCleaningKit {
            get {
                return ResourceManager.GetString("Chk-BootCleaningKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxers 06.
        /// </summary>
        internal static string Chk_Boxers06 {
            get {
                return ResourceManager.GetString("Chk-Boxers06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caddie.
        /// </summary>
        internal static string Chk_Caddie {
            get {
                return ResourceManager.GetString("Chk-Caddie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAT.
        /// </summary>
        internal static string Chk_CAT {
            get {
                return ResourceManager.GetString("Chk-CAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Bag.
        /// </summary>
        internal static string Chk_CombatBag {
            get {
                return ResourceManager.GetString("Chk-CombatBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat boots noted in your service booklet.
        /// </summary>
        internal static string Chk_CombatBoots {
            get {
                return ResourceManager.GetString("Chk-CombatBoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Glasses 14.
        /// </summary>
        internal static string Chk_CombatGlasses14 {
            get {
                return ResourceManager.GetString("Chk-CombatGlasses14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat GLoves 16.
        /// </summary>
        internal static string Chk_CombatGloves16 {
            get {
                return ResourceManager.GetString("Chk-CombatGloves16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat helmet with camo canvas.
        /// </summary>
        internal static string Chk_CombatHelmet {
            get {
                return ResourceManager.GetString("Chk-CombatHelmet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dress (for women).
        /// </summary>
        internal static string Chk_Dress {
            get {
                return ResourceManager.GetString("Chk-Dress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Insignia.
        /// </summary>
        internal static string Chk_FunctionInsignia {
            get {
                return ResourceManager.GetString("Chk-FunctionInsignia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamelle.
        /// </summary>
        internal static string Chk_Gamelle {
            get {
                return ResourceManager.GetString("Chk-Gamelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gourde.
        /// </summary>
        internal static string Chk_Gourd {
            get {
                return ResourceManager.GetString("Chk-Gourd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey Bags.
        /// </summary>
        internal static string Chk_GreyBags {
            get {
                return ResourceManager.GetString("Chk-GreyBags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Harness.
        /// </summary>
        internal static string Chk_GT {
            get {
                return ResourceManager.GetString("Chk-GT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearing Protection.
        /// </summary>
        internal static string Chk_HearingProtection {
            get {
                return ResourceManager.GetString("Chk-HearingProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knaggis.
        /// </summary>
        internal static string Chk_Knaggis {
            get {
                return ResourceManager.GetString("Chk-Knaggis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg Elastics.
        /// </summary>
        internal static string Chk_LegElastics {
            get {
                return ResourceManager.GetString("Chk-LegElastics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Pants 06.
        /// </summary>
        internal static string Chk_LongPants06 {
            get {
                return ResourceManager.GetString("Chk-LongPants06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow marking jersey.
        /// </summary>
        internal static string Chk_MarkingJersey {
            get {
                return ResourceManager.GetString("Chk-MarkingJersey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Militia insignia.
        /// </summary>
        internal static string Chk_MilitiaInsignia {
            get {
                return ResourceManager.GetString("Chk-MilitiaInsignia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth Guard.
        /// </summary>
        internal static string Chk_MouthGuard {
            get {
                return ResourceManager.GetString("Chk-MouthGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NBC Gas Mask.
        /// </summary>
        internal static string Chk_NBCMask {
            get {
                return ResourceManager.GetString("Chk-NBCMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NBC Gas Mask holder for Combat Harness.
        /// </summary>
        internal static string Chk_NBCMaskGTHolder {
            get {
                return ResourceManager.GetString("Chk-NBCMaskGTHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon with Bolt and Magazine.
        /// </summary>
        internal static string Chk_PersonalWeapon {
            get {
                return ResourceManager.GetString("Chk-PersonalWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket knife 08 with case.
        /// </summary>
        internal static string Chk_PocketKnife08 {
            get {
                return ResourceManager.GetString("Chk-PocketKnife08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polar vest 06.
        /// </summary>
        internal static string Chk_PolarVest06 {
            get {
                return ResourceManager.GetString("Chk-PolarVest06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPI.
        /// </summary>
        internal static string Chk_PPI {
            get {
                return ResourceManager.GetString("Chk-PPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purse (for women).
        /// </summary>
        internal static string Chk_Purse {
            get {
                return ResourceManager.GetString("Chk-Purse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulation bags.
        /// </summary>
        internal static string Chk_RegulationBags {
            get {
                return ResourceManager.GetString("Chk-RegulationBags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarf.
        /// </summary>
        internal static string Chk_Scarf {
            get {
                return ResourceManager.GetString("Chk-Scarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Booklet.
        /// </summary>
        internal static string Chk_ServiceBooklet {
            get {
                return ResourceManager.GetString("Chk-ServiceBooklet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeping Bag.
        /// </summary>
        internal static string Chk_SleepingBag {
            get {
                return ResourceManager.GetString("Chk-SleepingBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal Gloves 17.
        /// </summary>
        internal static string Chk_ThermalGloves17 {
            get {
                return ResourceManager.GetString("Chk-ThermalGloves17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-Shirt 06.
        /// </summary>
        internal static string Chk_TShirt06 {
            get {
                return ResourceManager.GetString("Chk-TShirt06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-Shirt 90.
        /// </summary>
        internal static string Chk_TShirt90 {
            get {
                return ResourceManager.GetString("Chk-TShirt90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform A with pants, vest, rain jacket, belt, 2x tie, 2x short sleeve shirts, 2x long sleeve shirts.
        /// </summary>
        internal static string Chk_UniformA {
            get {
                return ResourceManager.GetString("Chk-UniformA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bag for Uniform A.
        /// </summary>
        internal static string Chk_UniformABag {
            get {
                return ResourceManager.GetString("Chk-UniformABag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform B with shirt, pants, belt, and waterproof vest.
        /// </summary>
        internal static string Chk_UniformB {
            get {
                return ResourceManager.GetString("Chk-UniformB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon cleaning kit.
        /// </summary>
        internal static string Chk_WeaponCleaningKit {
            get {
                return ResourceManager.GetString("Chk-WeaponCleaningKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shooting festival / club competition.
        /// </summary>
        internal static string CompetitionShooting {
            get {
                return ResourceManager.GetString("CompetitionShooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Failed.
        /// </summary>
        internal static string FailedSearch {
            get {
                return ResourceManager.GetString("FailedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Federal Program 50m.
        /// </summary>
        internal static string FederalProgram50m {
            get {
                return ResourceManager.GetString("FederalProgram50m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Shooting.
        /// </summary>
        internal static string FieldShooting {
            get {
                return ResourceManager.GetString("FieldShooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun.
        /// </summary>
        internal static string Gun {
            get {
                return ResourceManager.GetString("Gun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you have given the appropriate permissions or that your device&apos;s location has been turned on..
        /// </summary>
        internal static string NoLocationMessage {
            get {
                return ResourceManager.GetString("NoLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get location.
        /// </summary>
        internal static string NoLocationTitle {
            get {
                return ResourceManager.GetString("NoLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatory Program.
        /// </summary>
        internal static string ObligatoryProgram {
            get {
                return ResourceManager.GetString("ObligatoryProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistol.
        /// </summary>
        internal static string Pistol {
            get {
                return ResourceManager.GetString("Pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a WIP demonstrating some features of the proposed PrepaCH app.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Young Shooters.
        /// </summary>
        internal static string YoungShooters {
            get {
                return ResourceManager.GetString("YoungShooters", resourceCulture);
            }
        }
    }
}
